"""report.py — the forward-test scoreboard.

    python3 -m executor.report          # print the report (markdown)
    python3 -m executor.report --write  # also refresh docs/forward-test.md

The engine refreshes docs/forward-test.md once per day automatically, so the
repo always carries the current track record. Every number comes from the
executor's own journal — this file computes aggregates, it invents nothing.
The 90-day demo-forward run is the evidence that decides whether anything
here deserves real money. Until then it is just a bot doing its homework.
"""
from __future__ import annotations

import sys
from datetime import datetime, timezone

from . import config
from .store import Store

DOC_PATH = config.REPO_DIR / "docs" / "forward-test.md"


def render(store: Store, live_equity: float | None = None) -> str:
    ft = store.get_state("forward_test_start") or {}
    start_ts = ft.get("ts", "")
    start_eq = ft.get("equity")
    if live_equity is None:
        live_equity = store.last_equity()
    days = None
    if start_ts:
        t0 = datetime.strptime(start_ts, "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=timezone.utc)
        days = (datetime.now(timezone.utc) - t0).days + 1

    lines = ["# Forward test — live demo track record", ""]
    lines.append("_Auto-generated by the executor from its own journal. "
                 "Demo account; nothing here is financial advice or a promise "
                 "of future returns._")
    lines.append("")
    if start_ts:
        ret = ((live_equity - start_eq) / start_eq * 100.0
               if live_equity and start_eq else None)
        lines.append("| | |")
        lines.append("|---|---|")
        lines.append("| Started | %s (day **%s** of 90) |" % (start_ts[:10], days))
        lines.append("| Start equity | %.2f |" % start_eq if start_eq else "| Start equity | — |")
        if live_equity is not None:
            lines.append("| Current equity | %.2f |" % live_equity)
        if ret is not None:
            lines.append("| Return since start | %+.2f%% |" % ret)
    st = store.stats()
    lines += ["", "## All-time (executor trades only)", "",
              "| trades | wins | win rate | P&L | profit factor | best | worst |",
              "|---|---|---|---|---|---|---|",
              "| %s | %s | %s | %s | %s | %s | %s |" % (
                  st["trades"], st["wins"],
                  ("%s%%" % st["win_rate"]) if st["win_rate"] is not None else "—",
                  st["pnl"], st["profit_factor"] or "—", st["best"], st["worst"])]

    combos = store.combos()
    if combos:
        lines += ["", "## By strategy × symbol", "",
                  "| strategy | symbol | trades | wins | P&L |", "|---|---|---|---|---|"]
        lines += ["| %s | %s | %s | %s | %s |" %
                  (c["strategy"], c["symbol"], c["n"], c["wins"], c["pnl"]) for c in combos]

    reports = store.daily_reports(30)
    if reports:
        lines += ["", "## Daily reports (last 30)", "",
                  "| date | trades | wins | win rate | P&L | equity close |",
                  "|---|---|---|---|---|---|"]
        for r in reports:
            lines.append("| %s | %s | %s | %s | %s | %s |" % (
                r["date"], r["trades"], r["wins"],
                ("%s%%" % r["win_rate"]) if r["win_rate"] is not None else "—",
                r["pnl"], round(r["equity_close"], 2) if r["equity_close"] else "—"))

    lessons = store.lesson_counts(12)
    if lessons:
        lines += ["", "## Self-review lessons (all time)", "",
                  "| mistake tag | count |", "|---|---|"]
        lines += ["| %s | %s |" % (l["tag"], l["c"]) for l in lessons]

    gate_rows = store.strategy_statuses()
    enabled = [r for r in gate_rows if r["status"] == "enabled"]
    lines += ["", "## Gate status",
              "", "%d of %d combos currently allowed to trade: %s" % (
                  len(enabled), len(gate_rows),
                  ", ".join("%s/%s" % (r["strategy"], r["symbol"]) for r in enabled) or "none"),
              "", "_Updated %s UTC_" % datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M")]
    return "\n".join(lines) + "\n"


def write_doc(store: Store, live_equity: float | None = None) -> None:
    DOC_PATH.parent.mkdir(parents=True, exist_ok=True)
    DOC_PATH.write_text(render(store, live_equity))


if __name__ == "__main__":
    s = Store()
    md = render(s)
    print(md)
    if "--write" in sys.argv:
        write_doc(s)
        print("wrote %s" % DOC_PATH)
